// Mocks generated by Mockito 5.4.6 from annotations
// in my_darts/test/features/game/presentation/providers/game_setup_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_darts/features/game/domain/entities/competitor.dart' as _i7;
import 'package:my_darts/features/game/domain/entities/game.dart' as _i2;
import 'package:my_darts/features/game/domain/usecases/create_game_use_case.dart'
    as _i6;
import 'package:my_darts/features/players/domain/entities/player.dart' as _i5;
import 'package:my_darts/features/players/domain/repositories/player_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGame_0 extends _i1.SmartFake implements _i2.Game {
  _FakeGame_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlayerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerRepository extends _i1.Mock implements _i3.PlayerRepository {
  MockPlayerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Player>> getAllPlayers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPlayers, []),
            returnValue: _i4.Future<List<_i5.Player>>.value(<_i5.Player>[]),
          )
          as _i4.Future<List<_i5.Player>>);

  @override
  _i4.Future<_i5.Player?> getPlayer(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlayer, [playerId]),
            returnValue: _i4.Future<_i5.Player?>.value(),
          )
          as _i4.Future<_i5.Player?>);

  @override
  _i4.Future<void> createPlayer(_i5.Player? player) =>
      (super.noSuchMethod(
            Invocation.method(#createPlayer, [player]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePlayerName(String? playerId, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlayerName, [playerId, name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> touchPlayer(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#touchPlayer, [playerId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePlayer(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlayer, [playerId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.Player>> watchAllPlayers() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllPlayers, []),
            returnValue: _i4.Stream<List<_i5.Player>>.empty(),
          )
          as _i4.Stream<List<_i5.Player>>);
}

/// A class which mocks [CreateGameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateGameUseCase extends _i1.Mock implements _i6.CreateGameUseCase {
  MockCreateGameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Game> execute(
    _i2.Game? game,
    List<_i7.Competitor>? competitors,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [game, competitors]),
            returnValue: _i4.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#execute, [game, competitors]),
              ),
            ),
          )
          as _i4.Future<_i2.Game>);
}
