// Mocks generated by Mockito 5.4.6 from annotations
// in dart_lodge/test/features/statistics/presentation/providers/player_stats_page_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dart_lodge/core/utils/constants.dart' as _i6;
import 'package:dart_lodge/features/statistics/domain/entities/game_stats.dart'
    as _i2;
import 'package:dart_lodge/features/statistics/domain/entities/player_leg_snapshot.dart'
    as _i7;
import 'package:dart_lodge/features/statistics/domain/entities/player_stats.dart'
    as _i3;
import 'package:dart_lodge/features/statistics/domain/repositories/statistics_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGameStats_0 extends _i1.SmartFake implements _i2.GameStats {
  _FakeGameStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayerStats_1 extends _i1.SmartFake implements _i3.PlayerStats {
  _FakePlayerStats_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StatisticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatisticsRepository extends _i1.Mock
    implements _i4.StatisticsRepository {
  MockStatisticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.GameStats> getGameStats(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getGameStats, [gameId]),
            returnValue: _i5.Future<_i2.GameStats>.value(
              _FakeGameStats_0(
                this,
                Invocation.method(#getGameStats, [gameId]),
              ),
            ),
          )
          as _i5.Future<_i2.GameStats>);

  @override
  _i5.Stream<_i2.GameStats> watchGameStats(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#watchGameStats, [gameId]),
            returnValue: _i5.Stream<_i2.GameStats>.empty(),
          )
          as _i5.Stream<_i2.GameStats>);

  @override
  _i5.Future<_i3.PlayerStats> getPlayerStats(
    String? playerId, {
    required _i6.GameType? gameType,
    DateTime? from,
    DateTime? to,
    int? startingScore,
    String? variant,
    int? legLimit,
    String? cricketTargetMode = 'fixed',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPlayerStats,
              [playerId],
              {
                #gameType: gameType,
                #from: from,
                #to: to,
                #startingScore: startingScore,
                #variant: variant,
                #legLimit: legLimit,
                #cricketTargetMode: cricketTargetMode,
              },
            ),
            returnValue: _i5.Future<_i3.PlayerStats>.value(
              _FakePlayerStats_1(
                this,
                Invocation.method(
                  #getPlayerStats,
                  [playerId],
                  {
                    #gameType: gameType,
                    #from: from,
                    #to: to,
                    #startingScore: startingScore,
                    #variant: variant,
                    #legLimit: legLimit,
                    #cricketTargetMode: cricketTargetMode,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i3.PlayerStats>);

  @override
  _i5.Future<List<_i7.PlayerLegSnapshot>> getPlayerLegHistory(
    String? playerId, {
    _i6.GameType? gameType,
    int? startingScore,
    String? variant,
    int? limit,
    String? cricketTargetMode = 'fixed',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPlayerLegHistory,
              [playerId],
              {
                #gameType: gameType,
                #startingScore: startingScore,
                #variant: variant,
                #limit: limit,
                #cricketTargetMode: cricketTargetMode,
              },
            ),
            returnValue: _i5.Future<List<_i7.PlayerLegSnapshot>>.value(
              <_i7.PlayerLegSnapshot>[],
            ),
          )
          as _i5.Future<List<_i7.PlayerLegSnapshot>>);

  @override
  _i5.Future<List<int>> getPlayerX01StartingScores(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlayerX01StartingScores, [playerId]),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<List<String>> getPlayerCricketVariants(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlayerCricketVariants, [playerId]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<_i3.PlayerStats> getPlayerStatsForGame(
    String? playerId,
    String? gameId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlayerStatsForGame, [playerId, gameId]),
            returnValue: _i5.Future<_i3.PlayerStats>.value(
              _FakePlayerStats_1(
                this,
                Invocation.method(#getPlayerStatsForGame, [playerId, gameId]),
              ),
            ),
          )
          as _i5.Future<_i3.PlayerStats>);

  @override
  _i5.Stream<_i3.PlayerStats> watchPlayerStats(
    String? playerId, {
    required _i6.GameType? gameType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #watchPlayerStats,
              [playerId],
              {#gameType: gameType},
            ),
            returnValue: _i5.Stream<_i3.PlayerStats>.empty(),
          )
          as _i5.Stream<_i3.PlayerStats>);
}
