// Mocks generated by Mockito 5.4.6 from annotations
// in dart_lodge/test/features/achievements/presentation/providers/achievement_watcher_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dart_lodge/core/utils/constants.dart' as _i7;
import 'package:dart_lodge/features/achievements/domain/repositories/achievement_repository.dart'
    as _i12;
import 'package:dart_lodge/features/game/domain/entities/competitor.dart'
    as _i8;
import 'package:dart_lodge/features/game/domain/entities/game.dart' as _i6;
import 'package:dart_lodge/features/game/domain/entities/game_event.dart'
    as _i9;
import 'package:dart_lodge/features/game/domain/repositories/game_repository.dart'
    as _i4;
import 'package:dart_lodge/features/statistics/domain/entities/game_stats.dart'
    as _i2;
import 'package:dart_lodge/features/statistics/domain/entities/player_leg_snapshot.dart'
    as _i11;
import 'package:dart_lodge/features/statistics/domain/entities/player_stats.dart'
    as _i3;
import 'package:dart_lodge/features/statistics/domain/repositories/statistics_repository.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGameStats_0 extends _i1.SmartFake implements _i2.GameStats {
  _FakeGameStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayerStats_1 extends _i1.SmartFake implements _i3.PlayerStats {
  _FakePlayerStats_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRepository extends _i1.Mock implements _i4.GameRepository {
  MockGameRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Game?> getActiveGame() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveGame, []),
            returnValue: _i5.Future<_i6.Game?>.value(),
          )
          as _i5.Future<_i6.Game?>);

  @override
  _i5.Future<_i6.Game?> getGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getGame, [gameId]),
            returnValue: _i5.Future<_i6.Game?>.value(),
          )
          as _i5.Future<_i6.Game?>);

  @override
  _i5.Future<List<_i6.Game>> getCompletedGames({
    int? limit = 20,
    int? offset = 0,
    _i7.GameType? filterByType,
    DateTime? dateFrom,
    DateTime? dateTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedGames, [], {
              #limit: limit,
              #offset: offset,
              #filterByType: filterByType,
              #dateFrom: dateFrom,
              #dateTo: dateTo,
            }),
            returnValue: _i5.Future<List<_i6.Game>>.value(<_i6.Game>[]),
          )
          as _i5.Future<List<_i6.Game>>);

  @override
  _i5.Future<List<_i8.Competitor>> getCompetitors(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getCompetitors, [gameId]),
            returnValue: _i5.Future<List<_i8.Competitor>>.value(
              <_i8.Competitor>[],
            ),
          )
          as _i5.Future<List<_i8.Competitor>>);

  @override
  _i5.Future<void> createGame(
    _i6.Game? game,
    List<_i8.Competitor>? competitors,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createGame, [game, competitors]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> completeGame({
    required String? gameId,
    required String? winnerCompetitorId,
    required DateTime? endTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeGame, [], {
              #gameId: gameId,
              #winnerCompetitorId: winnerCompetitorId,
              #endTime: endTime,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> appendEventsAndCompleteGame({
    required List<_i9.GameEvent>? events,
    required String? gameId,
    required String? winnerCompetitorId,
    required DateTime? endTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#appendEventsAndCompleteGame, [], {
              #events: events,
              #gameId: gameId,
              #winnerCompetitorId: winnerCompetitorId,
              #endTime: endTime,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i6.Game?> watchActiveGame() =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveGame, []),
            returnValue: _i5.Stream<_i6.Game?>.empty(),
          )
          as _i5.Stream<_i6.Game?>);

  @override
  _i5.Stream<List<_i6.Game>> watchCompletedGames({
    _i7.GameType? filterByType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchCompletedGames, [], {
              #filterByType: filterByType,
            }),
            returnValue: _i5.Stream<List<_i6.Game>>.empty(),
          )
          as _i5.Stream<List<_i6.Game>>);
}

/// A class which mocks [StatisticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatisticsRepository extends _i1.Mock
    implements _i10.StatisticsRepository {
  MockStatisticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.GameStats> getGameStats(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getGameStats, [gameId]),
            returnValue: _i5.Future<_i2.GameStats>.value(
              _FakeGameStats_0(
                this,
                Invocation.method(#getGameStats, [gameId]),
              ),
            ),
          )
          as _i5.Future<_i2.GameStats>);

  @override
  _i5.Stream<_i2.GameStats> watchGameStats(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#watchGameStats, [gameId]),
            returnValue: _i5.Stream<_i2.GameStats>.empty(),
          )
          as _i5.Stream<_i2.GameStats>);

  @override
  _i5.Future<_i3.PlayerStats> getPlayerStats(
    String? playerId, {
    required _i7.GameType? gameType,
    DateTime? from,
    DateTime? to,
    int? startingScore,
    String? variant,
    int? legLimit,
    String? cricketTargetMode = 'fixed',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPlayerStats,
              [playerId],
              {
                #gameType: gameType,
                #from: from,
                #to: to,
                #startingScore: startingScore,
                #variant: variant,
                #legLimit: legLimit,
                #cricketTargetMode: cricketTargetMode,
              },
            ),
            returnValue: _i5.Future<_i3.PlayerStats>.value(
              _FakePlayerStats_1(
                this,
                Invocation.method(
                  #getPlayerStats,
                  [playerId],
                  {
                    #gameType: gameType,
                    #from: from,
                    #to: to,
                    #startingScore: startingScore,
                    #variant: variant,
                    #legLimit: legLimit,
                    #cricketTargetMode: cricketTargetMode,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i3.PlayerStats>);

  @override
  _i5.Future<
    ({
      int games501Played,
      bool hasNineDarter,
      int highestCheckout,
      int total180s,
      int totalDartsThrown,
      int totalWins,
    })
  >
  achievementMetricsForPlayer(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#achievementMetricsForPlayer, [playerId]),
            returnValue:
                _i5.Future<
                  ({
                    int games501Played,
                    bool hasNineDarter,
                    int highestCheckout,
                    int total180s,
                    int totalDartsThrown,
                    int totalWins,
                  })
                >.value((
                  games501Played: 0,
                  hasNineDarter: false,
                  highestCheckout: 0,
                  total180s: 0,
                  totalDartsThrown: 0,
                  totalWins: 0,
                )),
          )
          as _i5.Future<
            ({
              int games501Played,
              bool hasNineDarter,
              int highestCheckout,
              int total180s,
              int totalDartsThrown,
              int totalWins,
            })
          >);

  @override
  _i5.Future<List<_i11.PlayerLegSnapshot>> getPlayerLegHistory(
    String? playerId, {
    _i7.GameType? gameType,
    int? startingScore,
    String? variant,
    int? limit,
    String? cricketTargetMode = 'fixed',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPlayerLegHistory,
              [playerId],
              {
                #gameType: gameType,
                #startingScore: startingScore,
                #variant: variant,
                #limit: limit,
                #cricketTargetMode: cricketTargetMode,
              },
            ),
            returnValue: _i5.Future<List<_i11.PlayerLegSnapshot>>.value(
              <_i11.PlayerLegSnapshot>[],
            ),
          )
          as _i5.Future<List<_i11.PlayerLegSnapshot>>);

  @override
  _i5.Future<List<int>> getPlayerX01StartingScores(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlayerX01StartingScores, [playerId]),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<List<String>> getPlayerCricketVariants(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlayerCricketVariants, [playerId]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<_i3.PlayerStats> getPlayerStatsForGame(
    String? playerId,
    String? gameId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlayerStatsForGame, [playerId, gameId]),
            returnValue: _i5.Future<_i3.PlayerStats>.value(
              _FakePlayerStats_1(
                this,
                Invocation.method(#getPlayerStatsForGame, [playerId, gameId]),
              ),
            ),
          )
          as _i5.Future<_i3.PlayerStats>);

  @override
  _i5.Stream<_i3.PlayerStats> watchPlayerStats(
    String? playerId, {
    required _i7.GameType? gameType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #watchPlayerStats,
              [playerId],
              {#gameType: gameType},
            ),
            returnValue: _i5.Stream<_i3.PlayerStats>.empty(),
          )
          as _i5.Stream<_i3.PlayerStats>);
}

/// A class which mocks [AchievementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAchievementRepository extends _i1.Mock
    implements _i12.AchievementRepository {
  MockAchievementRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Set<String>> getUnlocked(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnlocked, [playerId]),
            returnValue: _i5.Future<Set<String>>.value(<String>{}),
          )
          as _i5.Future<Set<String>>);

  @override
  _i5.Stream<Set<String>> watchUnlocked(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#watchUnlocked, [playerId]),
            returnValue: _i5.Stream<Set<String>>.empty(),
          )
          as _i5.Stream<Set<String>>);

  @override
  _i5.Future<void> recordUnlock(
    String? playerId,
    String? id,
    DateTime? at, {
    String? gameId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recordUnlock,
              [playerId, id, at],
              {#gameId: gameId},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
